- name: installing httpd
  yum:
   name: httpd
   state: present
   
- name: adding line
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^Listen '
    state: present
    line: Listen 8080 
    backup: yes


- name: Restart service httpd, in all cases
  service:
    name: httpd
    state: restarted
